# Generated by Django 3.1.6 on 2021-02-13 12:04

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210213_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogAuthor'),
        ),
    ]
